#!/system/bin/sh

if [ "$1" != "su" ] ; then
    OPTION=""

    MY_ID=`su --mount-master -c id`
    echo $MY_ID | grep -q "uid=0(root)"
    if [ $? -eq 0 ] ; then
        OPTION="--mount-master"
    fi

    exec su $OPTION -c $0 su $*
    exit 1
fi

shift


ARG0="$0"
ARG1="$1"

echo
echo Tera Version: 0.6.0
echo

EXE=$ARG0
#EXE_NAME=`basename $EXE`
EXE_NAME=`echo ${ARG0##*/}`

function my_killall()
{
    if [ -e /system/bin/killall ] ; then
        killall $*
        return
    fi

    RET=1

    if [ "$1" == "" ] ; then
        (exit $RET)
        return
    fi

    SIG_NUM=""
    if [ "$2" != "" ] ; then
        SIG_NUM="$1"
        PROC_NAME="$2"
    else
        PROC_NAME="$1"
    fi

    ps > /dev/ps.tmp

    while read LINE ; do
        set -- $LINE
        echo $9 | grep -qw $PROC_NAME
        if [ $? -ne 0 ] ; then
            continue
        fi
        kill $SIG_NUM $2
        RET=$?
    done < /dev/ps.tmp

    rm /dev/ps.tmp

    (exit $RET)
}

function bind_sdcard()
{
    BIND_SDCARD_COUNT=0

    touch $SDCARD/MY-TERA/MY-TERA.var

    cat /proc/self/mounts > /dev/bind.tmp

    while read LINE ; do
        set -- $LINE
        if [ -d $2/MY-TERA -a ! -f $2/MY-TERA/MY-TERA.var ] ; then
            echo bind $2/MY-TERA
            mount -o bind $SDCARD/MY-TERA $2/MY-TERA
            BIND_SDCARD_COUNT=$[$BIND_SDCARD_COUNT+1]
        elif [ -d $2/0/MY-TERA -a ! -f $2/0/MY-TERA/MY-TERA.var ] ; then
            echo bind $2/0/MY-TERA
            mount -o bind $SDCARD/MY-TERA $2/0/MY-TERA
            BIND_SDCARD_COUNT=$[$BIND_SDCARD_COUNT+1]
        fi
    done < /dev/bind.tmp

    rm /dev/bind.tmp

    rm $SDCARD/MY-TERA/MY-TERA.var
}

function umount_sdcard()
{
    touch $SDCARD/MY-TERA/MY-TERA.var 2> /dev/null

    cat /proc/self/mounts > /dev/bind.tmp

    while read LINE ; do
        set -- $LINE
        if [ -f $2/MY-TERA.var ] ; then
            echo umount $2
            umount $2 2> /dev/null
        fi
    done < /dev/bind.tmp

    rm /dev/bind.tmp

    #rm $SDCARD/MY-TERA/MY-TERA.var
}

function uninstall()
{
    if [ -s /tmp/tera2.pid ] ; then
        kill -9 `cat /tmp/tera2.pid`
        sleep 0.1
        rm /tmp/tera2.pid /tmp/tera2
    fi

    umount_sdcard

    if [ -d /tmp/MY-TERA ] ; then
        rm -rf /tmp/MY-TERA
    fi

    my_killall hcfsapid 2> /dev/null
    sleep 0.1
    my_killall -9 hcfsapid 2> /dev/null
    my_killall hcfs 2> /dev/null
    sleep 0.1
    my_killall -9 hcfs 2> /dev/null

    sleep 0.1

    rm -rf /data/hcfs /data/hcfs.conf /data/hcfs_android_log /data/hcfsapid.log /dev/shm

    mount -o rw,remount /system
    rm -rf /system/hcfs/
    mount -o ro,remount /system

    if [ -f /tmp/MY-TERA.tmp ] ; then
        mount -o rw,remount /
        umount /tmp/ 2> /dev/null
        rmdir /tmp 2> /dev/null
        mount -o ro,remount /
    fi

    rm -rf $SDCARD/MY-TERA
}

function install()
{
    mount -o rw,remount /system
    mkdir -p /system/hcfs
    chmod 0755 /system/hcfs
    cp $EXE /sdcard/hcfs /sdcard/hcfsapid /sdcard/hcfsconf /sdcard/hcfs.conf /sdcard/HCFSvol /sdcard/libcurl.so /sdcard/libfuse.so /sdcard/libjansson.so /sdcard/libzip.so /system/hcfs/
    rm $EXE /sdcard/hcfs /sdcard/hcfsapid /sdcard/hcfsconf /sdcard/hcfs.conf /sdcard/HCFSvol /sdcard/libcurl.so /sdcard/libfuse.so /sdcard/libjansson.so /sdcard/libzip.so
    chown root:root /system/hcfs/hcfs.conf /system/hcfs/libcurl.so /system/hcfs/libfuse.so /system/hcfs/libjansson.so /system/hcfs/libzip.so
    chmod 644 /system/hcfs/libcurl.so /system/hcfs/libfuse.so /system/hcfs/libjansson.so /system/hcfs/libzip.so
    chown root:system /system/hcfs/hcfs /system/hcfs/hcfsapid /system/hcfs/hcfsconf /system/hcfs/HCFSvol
    chmod 0755 /system/hcfs/hcfs /system/hcfs/hcfsapid /system/hcfs/hcfsconf /system/hcfs/HCFSvol
    chown root:root /system/hcfs/$EXE_NAME
    chmod 0755 /system/hcfs/$EXE_NAME
    mount -o ro,remount /system

    ls /data/app/com.hopebaytech.hcfsmgmt*/lib/arm64/ &> /dev/null
    if [ $? -eq 0 ] ; then
        LIB_PATH="/data/app/com.hopebaytech.hcfsmgmt*/lib/arm64/"
    else
        LIB_PATH="/data/data/com.hopebaytech.hcfsmgmt/lib/"
    fi
    cp /sdcard/libHCFS_api.so $LIB_PATH
    rm /sdcard/libHCFS_api.so
    chown system:system $LIB_PATH/libHCFS_api.so
    chmod 755 $LIB_PATH/libHCFS_api.so

    mkdir -p /data/hcfs /data/hcfs/metastorage /data/hcfs/blockstorage
}

export LD_LIBRARY_PATH=/system/hcfs
export PATH=$PATH:/system/hcfs

trap "" SIGHUP

SDCARD="/sdcard"
while [ 1 ] ; do
    LINK=`readlink -f $SDCARD`
    if [ "$LINK" == "" -o "$LINK" == "$SDCARD" ] ; then
        break
    fi
    SDCARD=$LINK
done

echo "SDCARD=$SDCARD"

if [ "$ARG1" == "uninstall" ] ; then
    rm $EXE
    uninstall
    sync

    echo
    echo Tera Uninstall OK
    echo

    exit
fi

if [ "$ARG1" == "install" ] ; then
    if [ -e /system/hcfs -o -e /data/hcfs ] ; then
        rm $EXE

        echo
        echo Tera Already Install
        echo
        exit 1
    fi

    install

    rm -f $EXE

    echo
    echo Tera Install OK
    echo
fi

my_killall -0 hcfs 2> /dev/null
if [ $? -eq 0 ] ; then
    echo
    echo Tera Already Run
    echo

    exit 1
fi

if [ ! -d /tmp ] ; then
    mount -o rw,remount /
    mkdir -p /tmp
    chmod 0700 /tmp
    mount -t tmpfs -o mode=0755,gid=1000 tmpfs /tmp
    mount -o ro,remount /

    touch /tmp/MY-TERA.tmp
fi

mkdir -p $SDCARD/MY-TERA
chmod 0777 $SDCARD/MY-TERA

rm -rf /dev/shm
mkdir -p /dev/shm
chown root:system /dev/shm
chmod 0770 /dev/shm

hcfsconf enc /system/hcfs/hcfs.conf /data/hcfs.conf
while [ ! -e /data/hcfs.conf ]; do sleep 0.1; done

#MEDIA_RW_ID=`id media_rw | sed "s/^uid=\([0-9]*\).*/\1/g"`
hcfs -o big_writes,writeback_cache,rw,nosuid,nodev,noexec,noatime,default_permissions,allow_other &
while [ ! -e /dev/shm/hcfs_reporter ]; do sleep 0.1; done

HCFSvol create hcfs_data internal

HCFSvol mount hcfs_data $SDCARD/MY-TERA
chown root:sdcard_rw $SDCARD/MY-TERA
chmod 777 $SDCARD/MY-TERA

bind_sdcard
if [ -f /system/bin/notify -a $BIND_SDCARD_COUNT -eq 0 ] ; then
    mkdir /tmp/MY-TERA
    mount -o bind $SDCARD/MY-TERA /tmp/MY-TERA
    chmod 0 /tmp/MY-TERA

    cat << EOF > /tmp/tera2
#!/system/bin/sh
while [ 1 ] ; do
    notify -m 40000004 -c 1 $SDCARD
    umount $SDCARD/MY-TERA
    mount -o bind /tmp/MY-TERA $SDCARD/MY-TERA
done
EOF

    chmod 500 /tmp/tera2
    /tmp/tera2 &
    echo $! > /tmp/tera2.pid
fi

HCFSvol create hcfs_external multiexternal

rm -f /data/data/com.hopebaytech.hcfsmgmt/hcfsapid_sock
hcfsapid &
while [ ! -e /data/data/com.hopebaytech.hcfsmgmt/hcfsapid_sock ]; do sleep 0.1; done

#chown `ls -ld /data/data/com.hopebaytech.hcfsmgmt | tr -s " " | cut -d " " -f3,4 | tr " " ":"` /data/data/com.hopebaytech.hcfsmgmt/hcfsapid_sock
LS_APP=`ls -ld /data/data/com.hopebaytech.hcfsmgmt`
set -- $LS_APP
chown $3:$4 /data/data/com.hopebaytech.hcfsmgmt/hcfsapid_sock 2> /dev/null

sync

if [ "$ARG1" == "install" ] ; then
    #am start -n com.hopebaytech.hcfsmgmt/.main.MainActivity
    am start -n com.android.settings/.applications.InstalledAppDetails -d package:com.hopebaytech.hcfsmgmt
fi

echo
echo Tera Run OK
echo
